### ISSUE TITLE
Method to get the value of a string

### ISSUE THREAD

**Issue by newmannj** [ricardolarios/A1-part2#4]
There is currently no method to get the value of a string, which would be required for concat (even though there is no "private" there should still be a getter)

**Comment by newmannj** [comment]
Can you please let us know when these issues have been resolved or not close them? Otherwise we have to check to see when you commit.

**Comment by ricardolarios** [comment]
Fair point, just updated.

**Comment by ricardolarios** [comment]
In the interest of trying to stay consistent with the rest of the class, we have switched to use the header files from this repo for object and string: https://github.com/chasebish/cwc_object_string. We removed our get_value function from the string (since everything is public anyway, and to be consistent) so you can create a pull request on Chase's repo if you still want to add this functionality.
